# Netlify configuration file for your React application

[build]
  command = "npm run build"  # Ensure Vite is available in your dependencies
  publish = "dist"            # This should match your Vite output directory
  functions = "netlify/functions"  # Adjust if you have serverless functions

  ## Redirect rules for Single Page Applications
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = true  # Ensure this redirect is always applied

# Environment variables (optional)
[build.environment]
  NODE_ENV = "production"  # Set NODE_ENV to production for optimized builds
  NODE_VERSION = "18"      # Specify your desired Node version (if needed)
